---
title: "exam1"
author: "Tianqi(Tim)"
date: "9/14/2020"
output: html_document
---

```{r}
#Q1
library(psych)
por1<- c(15, 18, 10, 12, 7, 13, 9)
por2<- c(7, 19, 13, 16, 21, 10, 12, 15)
describe(por1)
describe(por2)
t.test(por1,por2)
rm(list=ls())
#Q2
rat<- read.csv ("https://raw.githubusercontent.com/Kakashi-sensei/STAT_587_2020_fall_exam1/master/Rats.txt", header= TRUE)
library(psych)
library(reshape2)

d1<-describe(rat$Trim)
d2<-describe(rat$Untrimmed)
ratmelt<-melt(rat,measure.vars = c('Trim','Untrimmed'),#melted variable
                variable.name='TUT')
a <- sub("Untrimmed","0",ratmelt$TUT)#replace Untrimmed/Trim to number
b <- sub("Trim","1",a)
ratmelt$TUT <-b
install.packages("car")
install.packages("carData")
library(car)
leveneTest(ratmelt$value,ratmelt$TUT)

t.test(rat$Trim, rat$Untrimmed,var.equal=FALSE,alternative = 'less')#unequal variances

t.test(rat$Trim, rat$Untrimmed,var.equal=TRUE,alternative = 'less')

t.test(rat$Trim, rat$Untrimmed,var.equal=TRUE,conf.level=0.9, alternative = 'less')

boxplot(value~TUT,data=ratmelt)#side-by-side boxplot

qqPlot(value~TUT, main="qq plot", col="blue", col.lines="red",data=ratmelt)#qq-plot for two groups
# create a Function to generate random permutations and calculate means

randomsamples<-function(y, trt, nsims=100){
  n <- tapply(y, trt, length)
  y_sims<-NULL
  for(i in 1:nsims){
    n_new <- sample(1:length(y), n[1])
    y_sims <- rbind(y_sims, c(mean(y[n_new]), mean(y[!(1:length(y)) %in% n_new])))
  }
  y_sims<-as.data.frame(y_sims)
  names(y_sims)<-names(n)
  return(y_sims)
}

#create a random shuffle of known values
samples <- randomsamples(ratmelt$value, ratmelt$TUT, nsims = 199)
diff_random <- samples$`1`-samples$`0`
# p-value
m <- sum(diff_random <= -47.9)

n <- length(diff_random)
(m+1)/(n+1)
rm(list=ls())
#Q3

hayf <- read.table ("https://raw.githubusercontent.com/Kakashi-sensei/STAT_587_2020_fall_exam1/master/hayfever.txt", header= TRUE)

boxplot(Score~Group,data=hayf)#side-by-side boxplot

t.test(Score~Group,var.equal=TRUE,conf.level=0.9, alternative = 'two.sided', data=hayf)

t.test(Score~Group,var.equal=TRUE,alternative = 'two.sided', data=hayf)

t.test(Score~Group,var.equal=TRUE,conf.level=0.99, alternative = 'two.sided', data=hayf)

qqPlot(Score~Group, main="qq plot", col="blue", col.lines="red", data=hayf)
rm(list=ls())
#Q4
ptwork <- read.table ("https://raw.githubusercontent.com/Kakashi-sensei/STAT_587_2020_fall_exam1/master/pinetrees.txt", header= TRUE)

boxplot(Diameter~Part,data=ptwork)#side-by-side boxplot

qqPlot(ptwork$Diameter, main="qq plot", col="blue", col.lines="red")

qqPlot(Diameter~Part, main="qq plot", col="blue", col.lines="red",data=ptwork)

lnptwork <- transform(ptwork, ln=log(Diameter))

t.test(ln~Part,var.equal=FALSE,alternative = 'greater', data=lnptwork)
rm(list=ls())
```








```{r}
#### Function to generate random permutations and calculate means ####
randomsamples<-function(y, trt, nsims=100){
  n <- tapply(y, trt, length)
  y_sims<-NULL
  for(i in 1:nsims){
    n_new <- sample(1:length(y), n[1])
    y_sims <- rbind(y_sims, c(mean(y[n_new]), mean(y[!(1:length(y)) %in% n_new])))
  }
  y_sims<-as.data.frame(y_sims)
  names(y_sims)<-names(n)
  return(y_sims)
}
```
